app.api.posts_get:
    path:     /posts
    methods:  GET
    defaults:
        _controller:  app.controller.api.post:allAction
        apiAuthorize: false

app.api.posts_x_get:
    path:     /posts/{id}
    methods:  GET
    defaults:
        _controller:  app.controller.api.post:getAction
        apiAuthorize: false
    requirements:
        id: \d+

app.api.posts_x_comments_get:
    path:     /posts/{postId}/comments
    methods:  GET
    defaults:
        _controller:  app.controller.api.comment:allAction
        apiAuthorize: false
    requirements:
        postId: \d+

app.api.posts_x_comments_post:
    path:     /posts/{postId}/comments
    methods:  POST
    defaults:
        _controller:     app.controller.api.comment:postAction
        apiAuthorize:    true
        apiRequestClass: App\Api\Request\CommentCreateRequest
    requirements:
        postId: \d+
