# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # EventListener
    app.event_listener.api_request:
        class:     AppBundle\EventListener\ApiRequestListener
        autowire:  true
        tags:
            - { name: kernel.event_subscriber }

    app.event_listener.api_exception:
        class:     AppBundle\EventListener\ApiExceptionListener
        arguments: [ "%kernel.debug%" ]
        autowire:  true
        tags:
            - { name: kernel.event_subscriber }

    app.event_listener.api_view:
        class:     AppBundle\EventListener\ApiViewListener
        autowire:  true
        tags:
            - { name: kernel.event_subscriber }

    # Command
    app.command.generate_sample_data:
        class:     AppBundle\Command\GenerateSampleDataCommand
        autowire:  true
        tags:
            - { name: console.command }

    # Controller
    app.controller.api.comment:
        class:     AppBundle\Controller\Api\CommentController
        autowire:  true

    app.controller.api.post:
        class:     AppBundle\Controller\Api\PostController
        autowire:  true

    # Handler
    app.handler.comment:
        class:     App\Api\Doctrine\Handler\CommentHandler
        autowire:  true

    app.handler.post:
        class:     App\Api\Doctrine\Handler\PostHandler
        autowire:  true

    # Services
    app.api_view_converter:
        class:     AppBundle\View\ApiViewConverter
        autowire:  true

    app.api_serializer:
        class:     AppBundle\View\ApiSerializer

    app.api_key_verifier:
        class:     AppBundle\Security\ApiKeyVerifier
        arguments: ["%api_key%"]
